### ISSUE TITLE
the xpath.select is not work

### ISSUE THREAD

**Issue by stephenkingsley** [goto100/xpath#47] opened 2016-06-18 03:48 UTC
I wrote a program to get a websize news list.
```javascript

var getRulesElement = (doc) => {
  config.rules.map( ele => {
    rulesElement[ele.name] = [];
    var node = xpath.select(ele.xpath, doc); //return array and length is 20
    var keys = Object.keys(config.dataTypes[ele.blockType]); // return array that is element xpath
    node.map( (value, index) => getNode(ele.name, value, keys, config.dataTypes[ele.blockType], index))
  });
  return true;
}

var getNode = (name, value, keys, elementXpath, index) => {
  keys.map( key => {
    if (key !== 'action') {
      console.log(xpath.select('string(//h3)', value));
    }
  });
}

```
when run this code, the result is all the same !
```javascript 

// run the code
EU referendum in limbo after MP murder
EU referendum in limbo after MP murder
EU referendum in limbo after MP murder
EU referendum in limbo after MP murder
EU referendum in limbo after MP murder

```
I want the result:
```javascript 

// run the code
EU referendum in limbo after MP murder
Australian PM regrets inviting anti-gay cleric for iftar
Pakistan: Pregnant woman killed for 'honour'
...

```

In the function `getNode()`, the parameter `value` is right, only `console.log(xpath.select('string(//h3)', value));` had problem.

**Comment by JLRishe** [comment] 2016-06-24 07:56
You're using an absolute XPath (`//h3`). That's why it's producing the same value every time. Please provide an example input document and the value you're using for `ele.xpath`.

**Comment by JLRishe** [comment] 2016-08-08 06:56
Closing because this is not a bug and the case opener has not responded.

**Closed by JLRishe** 2016-08-08 06:56 UTC
